import { Profile } from "@/db/schema";

export const femaleProfiles: Partial<Profile>[] = [
  {
    firstName: "Amara",
    lastName: "Kimani",
    age: 20,
    gender: "female",
    course: "Bachelor of Business Information Technology",
    yearOfStudy: 2,
    bio: "BBIT student who loves coding and entrepreneurship. Always up for a good laugh and interesting conversations about tech and business! 💻✨",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [], // You'll add the photo links here
  },
  {
    firstName: "Zuri",
    lastName: "Ochieng",
    age: 21,
    gender: "female",
    course: "Bachelor of Commerce",
    yearOfStudy: 3,
    bio: "Future CEO in the making! When I'm not studying business strategies, you'll find me at networking events or planning my next venture 💫",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Aisha",
    lastName: "Hassan",
    age: 19,
    gender: "female",
    course: "Bachelor of Business Information Technology",
    yearOfStudy: 1,
    bio: "First-year BBIT student with a passion for UI/UX design. Love creating beautiful digital experiences and exploring Nairobi's coffee shops ☕",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Makena",
    lastName: "Mwangi",
    age: 22,
    gender: "female",
    course: "Bachelor of Science in Computer Science",
    yearOfStudy: 4,
    bio: "CS final year, AI enthusiast, and part-time photographer. Looking for someone to explore Nairobi's tech scene with! 📱",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Imani",
    lastName: "Njeri",
    age: 20,
    gender: "female",
    course: "Bachelor of Commerce",
    yearOfStudy: 2,
    bio: "Business student with a creative soul. Love marketing, branding, and everything entrepreneurship. Always planning the next big idea! 💡",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Sanaa",
    lastName: "Kariuki",
    age: 21,
    gender: "female",
    course: "Bachelor of Science in Computer Science",
    yearOfStudy: 3,
    bio: "Tech enthusiast and web developer. When I'm not coding, I'm probably at a hackathon or teaching code to high school students 👩‍💻",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Nyota",
    lastName: "Owino",
    age: 20,
    gender: "female",
    course: "Bachelor of Commerce",
    yearOfStudy: 2,
    bio: "Finance major with a passion for sustainable business. Love discussing investment strategies and global markets 📈",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Zawadi",
    lastName: "Mutua",
    age: 19,
    gender: "female",
    course: "Bachelor of Business Information Technology",
    yearOfStudy: 1,
    bio: "Tech-savvy freshman who loves solving problems through innovation. Always excited to learn new programming languages! 💻",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Nina",
    lastName: "Wanjiku",
    age: 21,
    gender: "female",
    course: "Bachelor of Commerce",
    yearOfStudy: 3,
    bio: "Marketing enthusiast with a creative edge. Love branding, digital marketing, and creating content. Looking for someone who appreciates good strategy! 🎯",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Amani",
    lastName: "Gathoni",
    age: 20,
    gender: "female",
    course: "Bachelor of Science in Computer Science",
    yearOfStudy: 2,
    bio: "Software developer in training. Passionate about mobile app development and UX design. Let's talk tech and create something amazing! 📱",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
];

export const maleProfiles: Partial<Profile>[] = [
  {
    firstName: "Jabari",
    lastName: "Kamau",
    age: 21,
    gender: "male",
    course: "Bachelor of Science in Computer Science",
    yearOfStudy: 3,
    bio: "CS student and full-stack developer. Love building apps and solving complex problems. Always up for hackathons and tech meetups! 🚀",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Baraka",
    lastName: "Odhiambo",
    age: 20,
    gender: "male",
    course: "Bachelor of Business Information Technology",
    yearOfStudy: 2,
    bio: "Tech and business enthusiast. When I'm not coding, I'm probably working on my startup ideas or playing basketball 🏀",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Malik",
    lastName: "Otieno",
    age: 22,
    gender: "male",
    course: "Bachelor of Commerce",
    yearOfStudy: 4,
    bio: "Finance major with big dreams. Love analyzing markets and discussing business strategies. Looking for someone ambitious and driven 📊",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Jamal",
    lastName: "Ndung'u",
    age: 21,
    gender: "male",
    course: "Bachelor of Science in Computer Science",
    yearOfStudy: 3,
    bio: "Software engineer and cybersecurity enthusiast. Love ethical hacking and building secure systems. Let's talk tech and security! 🔒",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
  {
    firstName: "Kobi",
    lastName: "Wekesa",
    age: 20,
    gender: "male",
    course: "Bachelor of Business Information Technology",
    yearOfStudy: 2,
    bio: "BBIT student passionate about data science and AI. Always exploring new technologies and looking for innovative solutions 📊",
    interests: ["🎮 Gaming", "💻 Tech", "📚 Reading", "🎵 Music", "✈️ Travel"],
    instagram: "",
    isVisible: true,
    photos: [],
  },
];
